# Generated by Django 2.2.12 on 2021-12-04 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('grado', models.CharField(max_length=200)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.docente')),
            ],
        ),
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantitativa', models.FloatField(default=0)),
                ('cualitativa', models.CharField(max_length=200)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaturas.materias')),
            ],
        ),
    ]
